<?php

namespace Tests;

use Database\Seeders\UserRoleSeeder;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub


        $this->seed(UserRoleSeeder::class);
    }
}
