<?php

namespace Tests;

use App\Models\UserRole;
use Database\Seeders\DatabaseSeeder;
use Database\Seeders\UserRoleSeeder;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');

        $this->seed(DatabaseSeeder::class);
    }
}
